### ISSUE TITLE
[GB Request] TAC expansion from 7 to 9 individuals

### ISSUE THREAD

**Issue by brianbehlendorf** [ossf/Governance-Committee#10]
At the Governing Board meeting of April 7th, the topic of whether to expand the TAC from 7 to 9 was raised. The result of the conversation was to ask the Governance Committee for a recommendation - either of a specific answer to this question, or to a process for the GB to use to arrive at a decision.

**Comment by SecurityCRob** [comment]
the GC approved the expansion of the TAC from 7 to 9 members.  Details are described here: https://github.com/ossf/tac/issues/213
