### ISSUE TITLE
MVSR

### ISSUE THREAD

**Issue by sevansdell** [ossf/Governance-Committee#15]
Members of the GB are developing an OpenSSF Mission, Vision, Strategy, Roadmap (MVSR) with input from the community. This issue socialized progress made on the MVSR, with a focus on the "M", "V" and "S". (The "R" is still in progress). Please review and provide feedback on the sections of the document up to the Roadmap. https://docs.google.com/document/d/1_oLsODuHRv2kYYn8meBUc9T6e68BZQFsknYBG642acw/edit

**Comment by sevansdell** [comment]
The MVSR is in final draft and ready for vote to adopt by GC in the next meeting, Oct 5. Please take time to read through it over the next week and make any suggested changes or comments. Thank you!

MVSR Final Draft: https://docs.google.com/document/d/1_oLsODuHRv2kYYn8meBUc9T6e68BZQFsknYBG642acw/edit

**Comment by SecurityCRob** [comment]
MVS was approved at the Monterey F2F GB call
