### ISSUE TITLE
Ops Model / Sustainable Funding

### ISSUE THREAD

**Issue by sevansdell** [ossf/Governance-Committee#16]
On Sep 8, the GB voted to request a draft Operating Model/Sustainable Funding to be shared at the in person board meeting, that they could vote on in the following virtual GB meeting.

The GC is accountable for developing the draft Operating Model/Sustainable Funding in partnership with LF Staff and other members interested members of the TAC/GB.

The working draft: [Ops Model & Sustainable Funding DRAFT v1 - Google Docs](https://docs.google.com/document/d/1b-nFE-cJ6QN2c4-gydgSgklu5NPysdCamJhS3v5XPqQ/edit)

Timeline: meet twice a week and have draft submitted by Oct 16 for a pre-read to the GB. Inform the GB of the draft and answer questions during the in person GB meeting agenda. Additional updates will be made and shared with GC prior to submitting to the GB for a one week preread prior to the next GB meeting.

**Comment by hythloda** [comment]
I think we can close this out as done
