### ISSUE TITLE
[TAC Request] Review OSS-SIRT Plan

### ISSUE THREAD

**Issue by bobcallaway** [ossf/Governance-Committee#7]
At the March 21st, 2023 TAC Meeting, the TAC will vote on moving https://github.com/ossf/tac/issues/131 to the Governance Committee of the OpenSSF GB for review & non-binding recommendation to the GB.

**Comment by SecurityCRob** [comment]
With these issues sitting uncommented on for months and the original plan updates being submitted last December I infer this is not a priority for the foundation and that we should close this issue.

**Comment by SecurityCRob** [comment]
Closed due to lack of interest, change in priorities.  May be re-addressed after the Ops Model work is complete.
