### ISSUE TITLE
[TAC Request] Review OSS-Security Mailing List Funding Proposal

### ISSUE THREAD

**Issue by bobcallaway** [ossf/Governance-Committee#8]
At the March 21st, 2023 TAC Meeting, the TAC will vote on moving https://github.com/ossf/tac/issues/132 to the Governance Committee of the OpenSSF GB for review & non-binding recommendation to the GB.

**Comment by bobcallaway** [comment]
This was discussed at the March 21st 2023 TAC Meeting [(Notes)](https://docs.google.com/document/d/18BJlokTeG5e5ARD1VFDl5bIP75OFPCtzf77lfadQ4f0/edit#) and approved without objection.

**Comment by SecurityCRob** [comment]
final paperwork is in-flight, and ideally will be closed soon with details agreed upon and contracts signed.

**Comment by SecurityCRob** [comment]
This was approved by the GB, and is in-flight ATM to implement.
